package dev.weather.core

enum class ForecastVariable {
    TEMPERATURE,
    APPARENT_TEMPERATURE,
    MINIMUM_TEMPERATURE,
    MAXIMUM_TEMPERATURE,
    HUMIDITY,
    DEW_POINT,
    PRESSURE,
    PRECIPITATION_PROBABILITY,
    PRECIPITATION_AMOUNT,
    RAIN,
    SNOWFALL,
    WIND_SPEED,
    WIND_DIRECTION,
    WIND_GUST,
    CLOUD_COVER,
    VISIBILITY,
    UV_INDEX,
}
